### ISSUE TITLE
Unable to access repository

### ISSUE THREAD

**Issue by Hiroshi-Suzuki-kyndryl** [ibm-cloud-security/certificate-manager-to-secrets-manager#4]
The repository could not be accessed for the following procedure. Is this repository publicly available?

READMI.md
  Installation
    Show local run instructions - 2 

`git clone https://github.ibm.com/security-services/secrets-manager-cm-migration-scripts.git  `

**Comment by IdanAdar** [comment]
Link has been fixed. Thanks for letting us know.
