### ISSUE TITLE
Error running cm_inventory.js in IBM Cloud Functions

### ISSUE THREAD

**Issue by sneres2526** [ibm-cloud-security/certificate-manager-to-secrets-manager#8]
I'm following the steps-by-steps but I got the following error by running cm_inventory thru IBM Cloud Functions:
{
  "error": "Initialization has failed due to: SyntaxError: Missing initializer in const declaration\n    at initializeActionHandler (/nodejsAction/runner.js:63:80)\n    at doInit (/nodejsAction/src/service.js:174:16)\n    at initCode (/nodejsAction/src/service.js:93:24)\n    at /nodejsAction/platform/platform.js:125:17\n    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)\n    at next (/node_modules/express/lib/router/route.js:137:13)\n    at Route.dispatch (/node_modules/express/lib/router/route.js:112:3)\n    at Layer.handle [as handle_request] (/node_modules/express/lib/router/layer.js:95:5)\n    at /node_modules/express/lib/router/index.js:281:22\n    at Function.process_params (/node_modules/express/lib/router/index.js:335:12)"
}

I've passed CM_APIKEY, SCRIPT_NAME and IS_TEST_ACCOUNT parameters accordingly. Please, advise ASAP

**Comment by yonatanyell** [comment]
@sneres2526 Can you please try again and make sure you are copying the entire "cm_**migration**.js" code?

**Comment by sneres2526** [comment]
> @sneres2526 Can you please try again and make sure you are copying the entire "cm_**migration**.js" code?

Thanks @yonatanyell , there is no error now. Nevertheless, the results are blank (see at screenshot below). We have one Certificate Manager instance in this account with 47 certificates inside.

![Screen Shot 2022-09-06 at 12 42 27](https://user-images.githubusercontent.com/24512107/188678967-d81bc69d-2a8c-4646-a24c-fed5faec7396.png).

**Comment by yonatanyell** [comment]
@sneres2526 Can you please make sure you are using the api key of the correct account - the account with the relevant Certificate Manager's instance? 

You can create a new api key in [this link](https://cloud.ibm.com/iam/apikeys). Please make sure you are creating the api key in the correct account.
<img width="1485" alt="Screen Shot 2022-09-07 at 11 59 29" src="https://user-images.githubusercontent.com/69857977/188842800-ec424740-c894-4423-91d2-4799c6b4bb83.png">
